[Feat] 즐겨찾기 리스트 공유 페이지 작업
3dollar-in-my-pocket/3dollar-in-my-pocket-android pull request #78
Opened 2023-01-11 14:56 UTC by JeongJinyong

## 작업내용 [Issue](https://github.com/3dollar-in-my-pocket/3dollar-in-my-pocket-android/issues/77#issue-1529196885)
- 즐겨찾기 리스트 공유 페이지 구성
- 즐겨찾기 리스트로 첫 진입시, 위치권한 체크 및 받기
- 비로그인 상태로 즐겨찾기 리스트 진입 후 로그인하면 화면이 종료될때 Main화면으로 이동

### TODO
- 딥링크 처리 필요

### 리뷰
- 딥링크 처리 전 작업까진 다 되어있어서 여유있게 코드리뷰 하기위해서 미리 올려둡니다 :)

2023-01-19 04:32 UTC, Minoyam requested changes

2023-01-19 04:32 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerActivity.kt
> +            selectedItem?.apply {
소소한거지만 Null Check 용도로 apply를 사용하신거면 대중적으로 사용되는 let이나 if문을 사용하는게 일관성이 있지 않을까 생각합니다!

2023-01-19 04:32 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerViewModel.kt
> +    }
이 부분은 나중에 따로 빼서 다른 곳에서도 Event 처리할 때 사용하면 좋을 꺼 같습니다!

2023-01-19 04:32 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/login/dialog/LoginRequestDialog.kt
> +        }
onCreateView에서는 inflate만 하고 다른 Ui 처리는 onViewCreated에서 처리하는 것이 좋습니다.
간혹 View가 생성되기 전에 코드가 실행될 수 있기 때문입니다.
https://developer.android.com/reference/kotlin/androidx/fragment/app/Fragment?hl=en#onCreateView(android.view.LayoutInflater,%20android.view.ViewGroup,%20android.os.Bundle)

2023-01-19 04:32 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/login/dialog/LoginRequestDialog.kt
> +            val account = GoogleSignIn.getLastSignedInAccount(GlobalApplication.getContext())
dialog의 context대신에 GlobalApplication.getContext() 사용하시는 이유가 있을까요?? (궁금)

2023-01-19 04:32 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/login/name/InputNameViewModel.kt
> +        }
postValue와 setValue를 같이 사용하신 이유가 있을까요?

2023-01-20 01:05 UTC, JeongJinyong commented on app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerActivity.kt
> +            selectedItem?.apply {
@Minoyam 일단 회사에서는 딱히 retrun값이 필요없을때 apply를 쓰고있어서 썻긴한데, 이 기회에 찾아보니까 
https://medium.com/mobile-app-development-publication/kotlin-dont-just-use-let-7e91f544e27f
해당 글을보고 run으로 변경하였습니다. scope function관련해서 찾아보니까 애매한부분이 많긴하네요 ㅎㅎ

2023-01-20 01:08 UTC, JeongJinyong commented on app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerViewModel.kt
> +    }
이게 공통으로 빼면 괜히 불필요한곳에서 까지 써야할것같아서 아직 고민중에 있습니다. ㅎㅎ 좋은 의견있으면 말씀해주세요 그쪽에 적용해볼께요 ㅎ

2023-01-20 01:11 UTC, JeongJinyong commented on app/src/main/java/com/zion830/threedollars/ui/login/dialog/LoginRequestDialog.kt
> +        }
수정했습니다 :)

2023-01-20 01:13 UTC, JeongJinyong commented on app/src/main/java/com/zion830/threedollars/ui/login/dialog/LoginRequestDialog.kt
> +            val account = GoogleSignIn.getLastSignedInAccount(GlobalApplication.getContext())
LoginRequestDialog 부분에서 로그인부분들은 전부 기존에있던 LoginActivity에서 복사해온거라 그렇긴합니다.
사실 저도 궁금했던 부분이긴 해서 여쭤보려고했었는데 같은 의문이 생겨버렸네요 ㅎㅎ 
로그인쪽도 최신화를 해두는 편이 좋을까요??

2023-01-20 01:15 UTC, JeongJinyong commented on app/src/main/java/com/zion830/threedollars/ui/login/name/InputNameViewModel.kt
> +        }
위와 동일하게 복붙하다 생긴 이슈긴한데 소스상에 생각보다 postValue가 많은거 보니 작업할때 특별한 이슈가 있었을까요??

2023-01-20 01:57 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/favorite/viewer/FavoriteViewerActivity.kt
> +            selectedItem?.apply {
scope function 용도별로 잘 쓰는게 쉽지는 않는거 같아요 ㅠ

2023-01-20 01:59 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/login/dialog/LoginRequestDialog.kt
> +            val account = GoogleSignIn.getLastSignedInAccount(GlobalApplication.getContext())
소셜 로그인 쪽은 저도 코드 숙지를 안해놔서 모르고 있었네요. 로그인쪽도 같이 변경하면 좋을꺼 같습니다!

2023-01-20 02:00 UTC, Minoyam commented on app/src/main/java/com/zion830/threedollars/ui/login/name/InputNameViewModel.kt
> +        }
음.. 이것도 있는 그대로 놔두던거라 한번에 최신화하는 작업을 하는것도 좋을꺼 같네요ㅋㅋㅋ

2023-01-20 02:02 UTC, Minoyam commented
수고 하셨습니다!! 최신 화 해야 하는 부분들은 하고 머지 하셔도 좋고, 냅뒀다가 나중에 시간 내서 최신화 할 것들 한번에 정리해서 하는 것도 좋을 꺼 같습니다!

2023-01-20 02:02 UTC, Minoyam approved these changes

2023-01-26 07:49 UTC, merged